# This workflow releases the project on Maven Central
# and prepare a new development version

name: Release to Maven Central
run-name: Release v${{ inputs.releaseVersion }} to Maven Central

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Release version"
        required: true
        default: ""
      developmentVersion:
        description: "New SNAPSHOT version"
        required: true
        default: ""
      autoRelease:
        type: boolean
        description: "Release staging repository immediately?"
        required: false
        default: false

jobs:
  release:
    uses: metricshub/workflows/.github/workflows/maven-central-release.yml@main
    with:
      releaseVersion: ${{ inputs.releaseVersion }}
      developmentVersion: ${{ inputs.developmentVersion }}
      autoRelease: ${{ inputs.autoRelease }}
      jdkVersion: "17"
    secrets: inherit
